import { Sora } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const sora = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-sora",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.variable} bg-black w-screen overflow-x-hidden`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
